////
//  Copyright ⓒ 2018-2019 ThePhD.
//
//  Distributed under the Boost Software License, Version 1.0. (See
//  accompanying file LICENSE or copy at
//  http://www.boost.org/LICENSE_1_0.txt)
//
//  See http://www.boost.org/libs/out_ptr/ for documentation.
////

# boost.out_ptr: the {cpp}11 abstraction for passing smart pointers as parameters to `$$T**$$` arguments 
ThePhD
:toc:
:toc-placement!:
:toclevels: 3
:idprefix:
:source-highlighter: pygments
:listing-caption: Code Example
:table-caption: Illustration
:docinfo: private-footer

This library automates the `.reset(...)` call with `phd::out_ptr::out_ptr(...)` wrapping an argument passed to a C-style function taking a `$$T**$$` argument. Additionally, it automates the `.release(...)` and `.reset(...)` paradigm with `phd::out_ptr::inout_ptr(...)` in cases where the `T**` argument passed to the function will both delete and then allocate the resource being handled.

Additional optimizations are implemented within the library to ensure good performance by default for a myriad of types, including `phd::movelib:unique_ptr` and `std::unique_ptr`. It also helps catch small errors in using `shared_ptr`-types reset calls, and works out-of-the-box for many other types including the upcoming `std::retain_ptr`, `phd::intrusive_ptr`, and any other types which follow the `.reset(...)`/`.release()` paradigm (or have constructors that behave similarly).

toc::[]

:leveloffset: +1

ifdef::env-github[]
link:out_ptr/overview.adoc[Overview]
endif::[]
ifndef::env-github[]
include::out_ptr/overview.adoc[]
endif::[]

ifdef::env-github[]
link:out_ptr/config.adoc[Configuration]
endif::[]
ifndef::env-github[]
include::out_ptr/config.adoc[]
endif::[]

ifdef::env-github[]
link:out_ptr/examples.adoc[Examples]
endif::[]
ifndef::env-github[]
include::out_ptr/examples.adoc[]
endif::[]

ifdef::env-github[]
link:out_ptr/benchmarks.adoc[Benchmarks]
endif::[]
ifndef::env-github[]
include::out_ptr/benchmarks.adoc[]
endif::[]

ifdef::env-github[]
link:out_ptr/caveats.adoc[Caveats]
endif::[]
ifndef::env-github[]
include::out_ptr/caveats.adoc[]
endif::[]

ifdef::env-github[]
link:out_ptr/rationale.adoc[Rationale]
endif::[]
ifndef::env-github[]
include::out_ptr/rationale.adoc[]
endif::[]

ifdef::env-github[]
link:out_ptr/reference.adoc[API Reference]
endif::[]
ifndef::env-github[]
include::out_ptr/reference.adoc[]
endif::[]

ifdef::env-github[]
link:out_ptr/customization.adoc[Customization]
endif::[]
ifndef::env-github[]
include::out_ptr/customization.adoc[]
endif::[]

:leveloffset: -1

[[appendix]]
## Copyright, License, and Acknowledgments

This documentation is

* Copyright ⓒ 2019 ThePhD

and is distributed under the http://www.boost.org/LICENSE_1_0.txt[Boost Software License, Version 1.0].
