////
//  Copyright ⓒ 2018-2019 ThePhD.
//
//  Distributed under the Boost Software License, Version 1.0. (See
//  accompanying file LICENSE or copy at
//  http://www.boost.org/LICENSE_1_0.txt)
//
//  See http://www.boost.org/libs/out_ptr/ for documentation.
////

# phd.out_ptr: the {cpp}11 abstraction for passing smart pointers as parameters to `$$T**$$` arguments 
ThePhD
:toc:
:toc-placement!:
:toclevels: 3
:idprefix:
:source-highlighter: pygments
:listing-caption: Code Example
:table-caption: Illustration
:docinfo: private-footer

So, you have code that looks like this:

```
foo_t* new_foo;
if (!create_foo(&new_foo)) {
  // etc. ...
}
```

And it's not just one bit. Hundreds, maybe even thousands of calls like this are scatted all throughout you code base. You know about smart pointers, and you want to turn it into something like this for better exception safety and all that RAII goodness you hear about:

```
std::unique_ptr<foo_t> new_foo;
if (!create_foo(new_foo)) {
  // etc. ...
}
```

Or, this:

```
std::unique_ptr<foo_t> new_foo;
if (!create_foo(&new_foo)) {
  // etc. ...
}
```

Doing this by hand is increasingly difficult with the number of calls you need to make. Writing tooling to generate code to wrap functions to return ``std::unique_ptr`` and morph the functions into something that returns a smart pointer is also a non-starter that will take you too much time.

With this library, you now can do exactly this at the call site:

```
using pop = phd::out_ptr;

std::unique_ptr<foo_t> new_foo;
if (!create_foo(pop::out_ptr(new_foo))) {
  // etc. ...
}
```

phd.out_ptr provides the a way to have C code retain identical semantics to the original C code written to handle these resources while helping code work with C APIs. It ensures ``new_foo`` is guaranteed to be treated in a RAII manner. Thus, we get increased exception safety, memory leak mitigation, and all the other benefits of RAII.

More formally, this library automates the `.reset(...)` call with `phd::out_ptr::out_ptr(...)` wrapping an argument passed to a C-style function taking a `$$T**$$` argument. Additionally, it automates the `.release(...)` and `.reset(...)` paradigm with `phd::out_ptr::inout_ptr(...)` in cases where the `T**` argument passed to the function will both delete and then allocate the resource being handled.

Additional optimizations are implemented within the library to ensure good performance by default for a myriad of types, including `boost::movelib:unique_ptr` and `std::unique_ptr`. It also helps catch small errors in using `shared_ptr`-types reset calls, and works out-of-the-box for many other types including the upcoming `std::retain_ptr`, `phd::intrusive_ptr`, and any other types which follow the `.reset(...)`/`.release()` paradigm (or have constructors that behave similarly).

toc::[]

:leveloffset: +1

ifdef::env-github[]
link:out_ptr/overview.adoc[Overview]
endif::[]
ifndef::env-github[]
include::out_ptr/overview.adoc[]
endif::[]

ifdef::env-github[]
link:out_ptr/config.adoc[Configuration]
endif::[]
ifndef::env-github[]
include::out_ptr/config.adoc[]
endif::[]

ifdef::env-github[]
link:out_ptr/examples.adoc[Examples]
endif::[]
ifndef::env-github[]
include::out_ptr/examples.adoc[]
endif::[]

ifdef::env-github[]
link:out_ptr/benchmarks.adoc[Benchmarks]
endif::[]
ifndef::env-github[]
include::out_ptr/benchmarks.adoc[]
endif::[]

ifdef::env-github[]
link:out_ptr/caveats.adoc[Caveats]
endif::[]
ifndef::env-github[]
include::out_ptr/caveats.adoc[]
endif::[]

ifdef::env-github[]
link:out_ptr/rationale.adoc[Rationale]
endif::[]
ifndef::env-github[]
include::out_ptr/rationale.adoc[]
endif::[]

ifdef::env-github[]
link:out_ptr/reference.adoc[API Reference]
endif::[]
ifndef::env-github[]
include::out_ptr/reference.adoc[]
endif::[]

ifdef::env-github[]
link:out_ptr/customization.adoc[Customization]
endif::[]
ifndef::env-github[]
include::out_ptr/customization.adoc[]
endif::[]

:leveloffset: -1

[[appendix]]
## Copyright, License, and Acknowledgments

This documentation is

* Copyright ⓒ 2019 ThePhD

and is distributed under the http://www.boost.org/LICENSE_1_0.txt[Boost Software License, Version 1.0].
