////
//  Copyright ⓒ 2018-2019 ThePhD.
//
//  Distributed under the Boost Software License, Version 1.0. (See
//  accompanying file LICENSE_1_0.txt or copy at
//  http://www.boost.org/LICENSE_1_0.txt)
//
//  See http://www.boost.org/libs/out_ptr/ for documentation.
////

[[examples]]
# Examples

Here are a few examples of the more powerful features of `boost::out_ptr::out_ptr` and `boost::out_ptr::inout_ptr`.

## ALL Smart Pointers, with Casting Support

The whole world of smart pointers is available to you. Taking advantage of the consistent `.reset()`, `.release()` and `.get()` set of functions almost all smart pointers have, `boost::out_ptr::out_ptr` and `boost::out_ptr::inout_ptr` work with more than just the typical standard pointers. They also know how to interop with legacy codebases which communicate through base class ``IUnknown**`` or ``void**``!

You can add a template parameter `out_ptr<T>()` to cast to a specific type, where `T` can be `HANDLE`, `int*`, `void*` and more:

ifdef::env-github[]
link:../../examples/source/com.intrusive_ptr.cpp[com.intrusive_ptr.cpp]
endif::[]
ifndef::env-github[]
[source,cpp,linenums]
----
include::../../examples/source/com.intrusive_ptr.cpp[lines=8..-1]
----
endif::[]

Notice how an extra parameter gets passed to the function:

ifdef::env-github[]
```
	HRESULT cci_result = CoCreateInstance(clsid, 0, CLSCTX_INPROC_SERVER,
		__uuidof(IDispatch), boost::out_ptr::out_ptr<void*>(dispatch_ptr, false));
```
endif::[]
ifndef::env-github[]
[source,cpp,linenums]
----
include::../../examples/source/com.intrusive_ptr.cpp[lines=34..35]
----
endif::[]

What this does is forward the `false` to ``intrusive_ptr``'s `reset(T* ptr, bool addRef)` call. You can invoke any `.reset()` with additional parameters so that you can work with any pointer type that takes `.reset(new_ptr, args...)`. Pass in as many `args` as you like to make the call work out!


## A `pthread` example

And for a Linux example, observe how you can pick up the ``new``ly created value after the `pthread` exits:

ifdef::env-github[]
link:../../examples/source/pthread.cpp[pthread.cpp]
endif::[]
ifndef::env-github[]
[source,cpp,linenums]
----
include::../../examples/source/pthread.cpp[lines=8..-1]
----
endif::[]

## Prevents errors with `shared_ptr` resetting the deleter.

If you have ever used any `shared_ptr` similar to the one in `boost` or the `std`, you'll know that if you call `my_shared_ptr.reset(some_raw_pointer)`, it will erase the old deleter and automatically place in the `std::default_delete<T>` (or similar). `boost::out_ptr` prevents that from happening by giving a strong, compile-time warning when you forget:

ifdef::env-github[]
link:../../examples/source/std.shared_ptr.cpp[std.shared_ptr.cpp]
endif::[]
ifndef::env-github[]
[source,cpp,linenums]
----
include::../../examples/source/std.shared_ptr.cpp[lines=8..-1]
----
endif::[]

This prevents you from making mistakes in your code and having strange non-delete bugs later on with your smart pointers.


## Customizing for your own pointer type

There is a whole section dedicated to customization, with its own example. See the <<customization.adoc#customization, customization documentation>> for more details.
