////
//  Copyright ⓒ 2018-2019 ThePhD.
//
//  Distributed under the Boost Software License, Version 1.0. (See
//  accompanying file LICENSE_1_0.txt or copy at
//  http://www.boost.org/LICENSE_1_0.txt)
//
//  See http://www.boost.org/libs/out_ptr/ for documentation.
////

[[ref]]
# Reference
:toc:
:toc-title:
:idprefix:

:leveloffset: +1

include::reference/out_ptr.adoc[`boost::out_ptr::out_ptr` and Associated Class Reference]

include::reference/inout_ptr.adoc[`boost::out_ptr::inout_ptr`  and Associated Class reference]

:leveloffset: -1

[[ref.syn]]
## Synopsis

The contents of the library are in namespace `boost::out_ptr`. There are two template functions: `out_ptr` and `inout_ptr`. There are two types that correspond to each of the 2 template functions: `out_ptr_t` and `inout_ptr_t`:

```
namespace boost { namespace out_ptr {
	
	template <class Smart, class Pointer, class... Args>
	struct out_ptr_t;

	template <class Smart, class Pointer, class... Args>
	struct inout_ptr_t;
	
	template <class Pointer, class Smart, class... Args>
	out_ptr_t<Smart, Pointer, Args...> out_ptr(Smart& s, Args&&... args) noexcept;
	
	template <class Smart, class... Args>
	out_ptr_t<Smart, POINTER_OF(Smart), Args...> out_ptr(Smart& s, Args&&... args) noexcept;

	template <class Pointer, class Smart, class... Args>
	inout_ptr_t<Smart, Pointer, Args...> inout_ptr(Smart& s, Args&&... args) noexcept;
	
	template <class Smart, class... Args>
	inout_ptr_t<Smart, POINTER_OF(SMART), Args...> inout_ptr(Smart& s, Args&&... args) noexcept 
}} // namespace boost::out_ptr
```
The following documentation describes `out_ptr` and `inout_ptr`.

[[ref.def]]
## Definitions

The following are definitions for some meta-functions done on types. If you see these used on

[ref.def.pointer_of_or]
- Let `POINTER_OF_OR(T, U)` denote a type that is:
* `T::pointer` if the qualified-id `T::pointer` is valid and denotes a type, or
* otherwise, `typename T::element_type*` if the qualified-id `T::element_type` is valid and denotes a type,
* otherwise, `U`.

[ref.def.pointer_of]
- Let `POINTER_OF(T)` denote a type that is defined as `POINTER_OF_OR(T, typename std::pointer_traits<T>::element_type*)`
